config/routes.rb
Port::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'static_pages#home'

  resources :posts

  match '/category/:id' => 'posts#category', :as => :category

  match 'blog' => 'posts#index'

  match 'about' => 'static_pages#about'
  match 'portfolio' => 'static_pages#portfolio'
  match 'contact' => 'static_pages#contact'
  match 'message' => 'contact#new', :via => :get
  match 'message' => 'contact#create', :via=> :post

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  # attr_accessible :title, :body

  belongs_to :post
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :category

	has_many :categorizations
	has_many :posts, :through => :categorizations  
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"
  
  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data
	
	def url_thumb
	  @url_thumb ||= Ckeditor::Utils.filethumb(filename)
	end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
	                  :styles => { :content => '800>', :thumb => '118x100#' }
	
	validates_attachment_size :data, :less_than => 2.megabytes
	validates_attachment_presence :data
	
	def url_content
	  url(:content)
	end
end

app/models/message.rb
class Message
	include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :email, :message, :name, :subject

  validates :name, :email, :message, :subject, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true

  def initialize(attributes = {})
  	attributes.each do |name, value|
  		send("#{name}=", value)
  	end
  end

  def persisted?
  	false
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	before_create :create_slug
  attr_accessible :content, :title,:status, :category_ids, :image

  has_attached_file :image, :styles => { :medium => "600x200#", :thumb => "300x100#",:small => "75x75#" }

  validates :title, :content, :image, :presence => true

  has_many :categorizations
  has_many :categories, :through => :categorizations

  STATUSES = ['published', 'draft', 'featured', 'archived']

  validates_inclusion_of :status, :in => STATUSES, 
  	:message => "{{value}} must be in #{STATUSES.join ','}"


  def to_param
    slug
  end

  def create_slug
    self.slug = self.title.parameterize
  end

  scope :published, where("status = ? OR status = ?", 'featured', 'published')
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :prepare_contact_form, :prepare_sidebar_data

	def prepare_contact_form
	  @message = Message.new
	end

	def prepare_sidebar_data
		@sidebar = Post.where('status = ? OR status = ?', 'featured', 'published').limit(10)
		@categories = Category.all
	end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
  	@message = Message.new
  end

  def create
  	@message = Message.new(params[:message])

  	if @message.valid?
  		NotificationsMailer.send_message(@message).deliver
  		flash[:success] = "Thank you for your interest! I'll get back to you as soon as I can"
  		redirect_to root_url
  	end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	require 'html_truncator'

	def index

		@posts = Post.where('status = ? OR status = ?', 'published', 'featured').order('created_at DESC')

		respond_to do |format|
			format.html # index.html.erb
			format.json { render :json => @posts}
		end
	end

	def show
		@post = Post.find_by_slug(params[:id])

		respond_to do |format|
			format.html # show.html.erb
			format.json { render :json => @post }
		end
	end

	def category
		require 'html_truncator'

		@posts = Category.find(params[:id]).posts.where('status = ? OR status = ?', 'featured', 'published')

		respond_to do |format|
			format.html #categories.html.erb
			format.json { render :json => @categories}
		end
	end

	
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    require 'html_truncator'

  	@posts = Post.published.limit(4)

  	respond_to do |format|
  		format.html #home.html.erb
  		format.json { render :json => @posts }
  	end
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def nav_link(link_text, link_path)
		class_name = current_page?(link_path) ? 'active' : ''

		content_tag(:li, :class => class_name) do
			link_to link_text, link_path
		end
	end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contact/new.html.erb
<%= form_for @message, :url => message_path, :validate => true do |form|
 %>
	<%= form.text_field :email, :placeholder => 'Email Address' %>

	<%= form.text_field :name, :placeholder => 'Name (first and last)' %>

	<%= form.text_field :subject, :placeholder => 'Subject' %>

	<%= form.text_area :message, :placeholder => 'Please enter a message' %>
	<br>
	<%= form.submit "Send", :class => 'button-small' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bryce Batson | Web Development Connoisseur</title>

  <meta name="description" content="Web developer based in Plattsburgh New York. Helping Plattsburgh residents develop world class websites with all the fluff but none of the hassles" />
	<meta name="keywords" content="Web Development, Web Design, Plattsburgh, New York, Plattsburgh Web Development" />
	<meta name="author" content="Bryce Batson"
	<meta name="robots" content="index, follow" />

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>

<a name="top"></a>
<div id="navbar">
		<div class="row">
			<div id="logo" class="three columns">
				<a href="#"><span class="orange">Bryce</span>Batson</a>
				<br>
				<span class="subtext">Web Development Connoisseur</span>
			</div>
			<div class="nine columns hide-for-small">
				<ul class="navigation">
					<%= nav_link 'Home', root_path %>
					<%= nav_link 'Portfolio', portfolio_path %>
					<%= nav_link 'Blog', blog_path %>
					<%= nav_link 'About', about_path %>
					<%= nav_link 'Contact', contact_path %>
				</ul>
			</div>
		</div>
</div>

<div class="eight columns show-for-small">
	<ul class="nav-bar">
		<li class="has-flyout">
			<a href="#">Menu</a>
			<a href="#" class="flyout-toggle"><span></span></a>
			<ul class="flyout">
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'About', about_path %></li>
				<li><%= link_to 'Contact', contact_path %></li>
				<li><%= link_to 'Portfolio', portfolio_path %></li>
			</ul>
		</li>
	</ul>
</div>

<% if flash[:success] %>
	<div class="alert alert-success"><%= flash[:success] %></div>
<% end %>


<div class="content container">
	<%= yield %>
</div>

<p id="back-top">
	<a href="#top" id="top"><span>&nbsp</span></a>
</p>

<div id="footer">
		<div class="row">
			<div class="four columns">
				<h3>Contact</h3>
				<%= render :template => 'contact/new' %>
			</div><!-- / Contact-form -->

			<div class="four columns hide-for-small">
				<h3>Twitter</h3>
				<div id="feed"></div>
				<script>
					jQuery(function($){
				        $("#feed").tweet({
				          join_text: "auto",
				          username: "brycebatson1",
				          avatar_size: 0,
				          count: 3,
				          loading_text: "loading tweets..."
				        });
				      });
				</script>
			</div><!-- /Twitter -->

			<div class="four columns">
				<h3>Who am I?</h3>
				<%= image_tag 'me.png', :class => 'me_image' %>
				<p class="who_am_i">Hey there! My name is Bryce Batson. I am a freelance web developer living in Plattsburgh New York. I have two beautiful children and a lovely fiance.</p>
				<p>I have been developing websites for almost 3 years and have worked in Ruby (my favorite), php, and almost all front end languages (HTML,CSS,Javascript). I absolutely love what I do, and I hope to prove it to you! Don't waste another moment, drop me a line. I look forward to working with you!</p>
				<p>Want to know more about me? Click <%= link_to "here", about_path %></p>
			</div><!-- /Introduction -->
		</div>
</div>
<div id="footer_bottom">
	<div class="container">
		<div class="row">
			<ul>
				<li>
					<%= link_to 'Bryce Batson', root_path %> &copy; 2012 | 
				</li>
				<li>
					<%= link_to 'Home', root_path %> | 
				</li>
				<li>
					<%= link_to 'About', about_path %> | 
				</li>
				<li>
					<%= link_to 'Contact', contact_path %>
				</li>
			</ul>
		</div>
	</div>
</div>

</body>
</html>

app/views/posts/_post.html.erb
<div class="eight columns">
  <div class="post">
    <h5><%= @post.title %></h5>
    <div class="post_info">
      
      Posted

      <span class="date">
         <%= time_ago_in_words @post.created_at %> ago
      </span>

      <% unless @post.categories.empty? %>
        in

        <ul>
          <% @post.categories.each do |category| %>
            <% unless category.category.empty? %>
            <li><%= link_to category.category, category_path(category.id) %></li>
            <% end %>
          <% end %>
        </ul>
      <% end %>
    </div>

    <% if @post.image? %>

    <%= image_tag('top-shadow.png') %>
        <div class="image">
            
                <%= image_tag @post.image.url(:medium) %>
            
        </div>
    <%= image_tag('bottom-shadow.png') %>
    <% end %>
    
    <p><%= raw @post.content %></p>

    <hr>

    <div id="disqus_thread"></div>
        <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
            var disqus_shortname = 'brycebatson'; // required: replace example with your forum shortname

            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    
  </div>
      
</div>

app/views/posts/_post_sidebar.html.erb
<h5>Recent Posts</h5>
<ul class="bordered_list">
	<% @sidebar.each do |post| %>
		<li><%= link_to post.title, post %></li>
	<% end %>
</ul>

<br>

<h5>Categories</h5>
<ul class="bordered_list">
	<% @categories.each do |cat| %>
	<li><%= link_to cat.category, category_path(cat.id) %></li>
	<% end %>
</ul>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
	<div id="blog_post" class="post">
	  <h5><%= post.title %></h5>
	  <div class="post_info">
	  	
	  	Posted

	  	<span class="orange">
	    	 <%= time_ago_in_words post.created_at %> ago
	    </span>

	    <% unless post.categories.empty? %>
	    	in

		    <ul>
			    <% post.categories.each do |category| %>
				    <li><%= link_to category.category, category_path(category.id) %></li>
				  <% end %>
		    </ul>
		  <% end %>
	  </div>

	  <% if post.image?%>
	  <%= image_tag('top-shadow.png') %>
	      <div class="image">
	          
	              <%= image_tag post.image.url(:medium) %>
	          
	      </div>
	  <%= image_tag('bottom-shadow.png') %>
	  <% end %>
	  
	  <p><%= raw HTML_Truncator.truncate(post.content, 300) %></p>
	  
	  <%= link_to 'Read More', post, :class => "btn button-small pull-right" %>
	</div>
	<script type="text/javascript">
     SyntaxHighlighter.all()
	</script>
<% end %>

app/views/posts/_sidebar.html.erb
<h5>Recent Posts</h5>
<ul class="bordered_list">
	<% @sidebar.each do |post| %>
		<li><%= link_to post.title, post %></li>
	<% end %>
</ul>

<br>

<h5>Categories</h5>
<ul class="bordered_list">
	<% @categories.each do |cat| %>
	<li><%= link_to cat.category, category_path(cat.id) %></li>
	<% end %>
</ul>

app/views/posts/category.html.erb
<div class="row">
	<div class="eight columns">
		<% unless @posts.empty? %>
			<%= render :partial => 'posts' %>
		<% else %>
			There are no posts in this category
		<% end %>
	</div>
	<div class="four columns">
	  	<%= render :partial => 'sidebar' %>
	</div>
</div>

app/views/posts/index.html.erb
<div class="row">
	<div class="eight columns">
		<%= render :partial => 'posts' %>
	</div>
	<div class="four columns">
	  	<%= render :partial => 'sidebar' %>
	</div>
</div>

app/views/posts/show.html.erb
<div class="row">
	
	<%= render :partial => 'post' %>

	<div class="four columns">
		<%= render :partial => 'post_sidebar' %>
	</div>
</div>

app/views/static_pages/about.html.erb
<div class="row">
	<div id="who_am_i" class="eight columns">
		<h4>Meet the man behind the scene</h4>
		<%= image_tag 'me.png', :class=>'pull-left me_image' %>
		<p>
			<span class="dropcap">M</span> y name is Bryce Batson. I was born in 1985 in Algonquin, IL. Since then I have lived in 5 different states: Michigan, Wisconsin, Illinois again, Michigan again, Vermont, and finally New York. I now live with my loving wife and two kids, Ethan and Addison. I graduated with a music business degree from Lyndon State College in 2011, but my true passion is and always has been computers.
		</p>
		<p>	
			I have been obsessed with computers my entire life. I built my first computer at 12 and my first website at 14. I decided to drop my passion for computers in search of a more reliable means of income and pursued architecture and business, but the whole time I could feel the pull of the web luring me back in. I finally gave in in 2010, and began developing websites again. 
		</p>
		<p>
			I most recently started developing applications using <a href="http://rubyonrails.org/">Ruby on Rails</a> which I am absolutely in love with, but still in the process of learning. I have mostly worked with <a href="http://www.php/net">PHP</a>, which is a very powerful but slightly cluttered language in my opinion. I have worked with multiple database tools and am proficient in SQL. 
		</p>
		<p>
			Although I know HTML, CSS, and Javascript/jQuery (design stuff), I do not have the same eye for detail that most designers do. I can make a solid UI and design, but my real proficiencies lie in the backend programming aspect of web development. 
		</p>
		<hr>
		<h5>I hope to work with you soon, make sure to leave me a <%= link_to 'message', contact_path %> and let me know what you think about my work!</h5>
	</div>
	<div class="four columns">
		<h4>My Skills</h4>
		<div class="progress progress-danger">
			<div class="bar" style="width:100%">
				<p>HTML</p>
			</div>
		</div>
		<div class="progress progress-danger">
			<div class="bar" style="width:80%">
				<p>CSS</p>
			</div>
		</div>
		<div class="progress progress-danger">
			<div class="bar" style="width:80%"><p>PHP</p></div>
		</div>
		<div class="progress progress-danger">
			<div class="bar" style="width:60%"><p>MySQL</p></div>
		</div>
		<div class="progress progress-danger">
			<div class="bar" style="width:60%"><p>Javascript/jQuery</p></div>
		</div>
		<div class="progress progress-danger">
			<div class="bar" style="width:40%"><p>Ruby --></p></div>
		</div>
	</div>
</div>	

app/views/static_pages/contact.html.erb
<div id="contact_info" class="row">
	<div class="six columns">
		<h5>Where Am I?</h5>
		<div class="row">
			<div class="twelve columns">
				<iframe width="100%" height="350" frameborder="0" scrolling="no" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=376+Margaret+St,+Plattsburgh,+NY&amp;aq=0&amp;oq=376+&amp;sll=42.746632,-75.770041&amp;sspn=4.501717,9.876709&amp;ie=UTF8&amp;hq=&amp;hnear=376+Margaret+St,+Plattsburgh,+New+York+12901&amp;t=m&amp;z=14&amp;ll=44.708877,-73.451803&amp;output=embed"></iframe>
			</div>
		</div>
		
		<div class="row">
			<div class="twelve columns">
				<h4><i class="icon-home"></i> Address</h4>
				<p class="orange">Bryce Batson</p>
				<p>376 Margaret St Apt D-21</p>
				<p>Plattsburgh, NY 12901</p>
				<br>
			</div>
			<div class="twelve columns">
				<h4><i class="icon-comment"></i> Contact</h4>	
				<p>Phone: 802.473.0249</p>
				<p>Email: <%= mail_to 'batson456@gmail.com' %></p>
			</div>
		</div>
	</div>

	<div id="contact_form" class="six columns">
		<h5>Get in touch!</h5>	
		<%= render :template => 'contact/new' %>
	</div>
</div>

<div class="row">
	
</div>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="twelve columns">
      <div class="introduction">
        <span>Welcome! My name is <span class="orange">Bryce Batson</span>. I am a freelance web developer living in Plattsburgh New York. Please take a look around, don't be shy. If you like what you see, <%= link_to 'let me know', contact_path %>.</span>
      </div>
  </div>
</div>

<div class="row hide-for-small">
    <div id="slider" class="twelve columns drop-shadow lifted">
        <div class="rotator">
            <ul id="rotmenu">
                <li>
                    <a href="rot1">Katy Milstead's Blog</a>
                    <div style="display:none;">
                        <div class="info_image">katy_aftermath.jpg</div>
                        <div class="info_description">
                            A personal blog for a good friend of mine. The theme was an interesting one, but I think we did a real good job with it. <a href="http://www.katyaftermath.com" class="more">Visit</a>
                        </div>
                    </div>
                </li>
                <li>
                    <a href="rot2">Danette's Photography</a>
                    <div style="display:none;">
                        <div class="info_image">danette.jpg</div>
                        <div class="info_description">
                            I made this site for Danette Duprey, a photographer living in Chazy, New York. It features a custom ajax driven admin panel and all the tools she needs to keep it running. Design courtesy of ThemeCatcher at <a href="http://www.themeforest.net">ThemeForest</a>
                            <br>
                            <a href="#" class="more">Visit</a>
                        </div>
                    </div>
                </li>

                <li>
                    <a href="rot3">The Wallers</a>
                    <div style="display:none;">
                        <div class="info_image">wallers.jpg</div>
                        <div class="info_description">
                            Created a family website for The Waller family including event calendar and personalized blogs for every member of the family.
                            <br>
                            <a href="#" class="more">Visit</a>
                        </div>
                    </div>
                </li>

                <li>
                    <a href="rot4">My Portfolio</a>
                    <div style="display:none;">
                        <div class="info_image">my-portfolio.jpg</div>
                        <div class="info_description">
                            This was my first portfolio design. I scrapped it and started again with this one. Much better now isn't it?
                            <br>
                        </div>
                    </div>
                </li>
            </ul>

            <div id="rot1">
                <img src="" width="800" height="300" class="bg" alt=""/>
                <div class="heading">
                    <h1></h1>
                </div>
                <div class="description">
                    <p></p>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Why Me?-->
<div id="why-me" class="row">

    <div class="four columns reason">
        <%= image_tag('orange-design.png') %>
        <h2>Design</h2>
        <hr>
        <p>You know what you want to make, but you just don't quite know how to make it. I will work with you on any project to design a clean and effective web design that you can be proud of, whethere it is a personal blog or professional business website.</p>
        <br>
        <%= image_tag 'bottom-shadow.png' %>
    </div>
    <div class="four columns reason">
        <%= image_tag('orange-code.png') %>
        <h2>Develop</h2>
        <hr>
        <p>There is so much more to web development these days than a simple design. With my skills as a PHP and Ruby developer, I can make sure you have all the features you are looking for in your project, from a blog to a shopping cart, we can make it work.</p>
        <br>
        <%= image_tag 'bottom-shadow.png' %>
    </div>
    <div class="four columns reason">
        <%= image_tag('orange-web.png') %>
        <h2>Deploy</h2>
        <hr>
        <p>Everything is finished, you want to show your new website off to the world, and I can make sure that you get that wish. Whether you need hosting, or you just want me to help you set it up, I will be your guide to make sure you get your finished product seen.</p>
        <br>
        <%= image_tag 'bottom-shadow.png' %>
    </div>

</div> <!-- /Why Me? -->


<div class="row">
    <div class="twelve columns">
        <h4>
            Latest Projects
            <span class="more-link">
                <%= link_to 'View All', portfolio_path %>
            </span>
        </h4>
    </div>
</div>


<ul class="thumbnails row">
    <li class="four columns">
        <div>
            <a href="#" class="zoom">
        <span class="roll"></span>
        <%= image_tag('wallers.jpg') %>
      </a>
      <%= image_tag('bottom-shadow.png') %>
      <p>Wallers Family Website (WIP)</p>
     </div>
    </li>
    <li class="four columns">
        <div>
            <a href="http://www.katyaftermath.com" class="zoom">
        <span class="roll"></span>
        <%= image_tag('katy_aftermath.jpg') %>
      </a>
      <%= image_tag('bottom-shadow.png') %>
      <p>Katy Milstead's Blog</p>
     </div>
    </li>
    <li class="four columns">
        <div>
            <a href="#" class="zoom">
        <span class="roll"></span>
        <%= image_tag('danette.jpg') %>
      </a>
      <%= image_tag('bottom-shadow.png') %>
      <p>Danette's Photography (No Longer Online)</p>
     </div>
    </li>

</ul>


<br>
<hr class="row">
<br>

<div class="row">
    <div class="six columns">
        <h4>Recent Posts
            <span class="more-link">
                <%= link_to 'View All', posts_path %>
            </span>
        </h4>
        <div class="twelve columns">
            <div id="recent_posts" class="row">
                <% @posts.each do |post| %>

                    <div class="twelve columns">

                        <% if post.image? %>

                        <div class="mobile-one three columns">
                            <div class="blog image">
                                    <%= image_tag post.image.url(:small, :style => 'float:left;') %>
                            </div>
                        </div>

                        <% end %>

                        <div class="nine mobile-three columns">
                            <p>
                                <%= link_to HTML_Truncator.truncate(post.title,8), post %>
                            </p>
                            <p>
                            <%= post.created_at.strftime("%b, %Y") %>
                            </p>
                        </div>
                    </div>

                <% end %>

            </div>
        </div>
    </div>


    <div class="six columns">
        <h4>Testimonials
            <span class="slider-buttons">
               
            </span>
        </h4>

        <div id="testimonials" class="twelve columns">
 
            <ul class="slides">
                <li>
                    <p>"Bryce created a website that just plain works. It's crisp, clean, beautiful, and everything I hoped it would be and more"
                    </p>
                    <br>
                    <i>-- Danette Duprey</i>
                </li>
                <li>
                    <p>"OMG, I'm in love!"</p>
                    <br>
                    <i>-- Katy Milstead</i>
                </li>
            </ul>

        </div>

    </div>
</div>

app/views/static_pages/portfolio.html.erb
<div class="row">
	<div class="twelve columns">
		<h4>My Portfolio</h4>	
	</div>
</div>

<ul id="gallery" class="thumbnails row">
	<li class="three columns">
		<div>
			<a href="#" class="zoom">
        <span class="roll"></span>
        <%= image_tag('wallers.jpg') %>
      </a>
      <%= image_tag('bottom-shadow.png') %>
      <p>Waller's Family Website (WIP)</p>
     </div>
	</li>

	<li class="three columns">
		<div class="image">
			<a href="http://www.katyaftermath.com" class="zoom">
        <span class="roll"></span>
        <%= image_tag('katy_aftermath.jpg') %>
      </a>
      <%= image_tag('bottom-shadow.png') %>
      <p>Katy Milstead's Blog</p>
     </div>
	</li>	

	<li class="three columns">
		<div class="image">
			<a href="#" class="zoom">
        <span class="roll"></span>
        <%= image_tag('danette.jpg') %>
      </a>
      <%= image_tag('bottom-shadow.png') %>
      <p>Danette's Photography (No longer online)</p>
     </div>
	</li>

	<li class="three columns">
		<div class="image">
			<a href="#" class="zoom">
        <span class="roll"></span>
        <%= image_tag('my-portfolio.jpg') %>
      </a>
     <%= image_tag('bottom-shadow.png') %>
      <p>My Original Portfolio Design</p>
     </div>
	</li>
</ul>
<br>
<hr class="row">
<br>

<h5 class="row center">
	This is just the beginning, there are plenty more to come!
</h5>